### ISSUE TITLE
Dataset 1 analysis needed

### ISSUE THREAD

**Issue by saadpocalypse** [saadpocalypse/Stanford_Data_Project#1]
Somebody needs to analyze dataset 1

**Comment by Kitchlew** [comment]
[Dataset 1 p value analysis.xlsx](https://github.com/saadpocalypse/Stanford_Data_Project/files/6284743/Dataset.1.p.value.analysis.xlsx)

**Comment by Kitchlew** [comment]
[Dataset 1 p value analysis.xlsx](https://github.com/saadpocalypse/Stanford_Data_Project/files/6284749/Dataset.1.p.value.analysis.xlsx)
