### ISSUE TITLE
Dataset 3 Analysis Required

### ISSUE THREAD

**Issue by saadpocalypse** [saadpocalypse/Stanford_Data_Project#2]
Someone needs to do an analysis of dataset 3.

**Comment by hamzi15** [comment]
![Uploading IMG_93C629300E7C-1.jpeg…]()

**Comment by hamzi15** [comment]
![IMG_93C629300E7C-1](https://user-images.githubusercontent.com/66818162/114312925-ded03800-9b0d-11eb-940a-9973fd2ef0d4.jpeg)
